using System.Diagnostics.CodeAnalysis;
using System.Text.RegularExpressions;

namespace Chatify.BuildingBlocks.Primitives;

/// <summary>
/// Provides utility methods for generating and validating correlation IDs used for distributed tracing.
/// </summary>
/// <remarks>
/// <para>
/// Correlation IDs are unique identifiers that associate a request, operation, or transaction
/// across multiple services, components, and log entries. They are essential for debugging
/// distributed systems and understanding the flow of requests through the application.
/// </para>
/// <para>
/// <b>Format:</b><br/>
/// Correlation IDs generated by this utility follow the format: <c>corr_{guid}</c><br/>
/// Example: <c>corr_a1b2c3d4-e5f6-7890-abcd-ef1234567890</c>
/// </para>
/// <para>
/// The "corr_" prefix makes correlation IDs easily identifiable in logs and metadata,
/// improving debugging and log analysis. The GUID portion ensures global uniqueness.
/// </para>
/// <para>
/// <b>When to Generate:</b>
/// <list type="bullet">
///   <item>At the entry point of an HTTP request (if not provided by the client)</item>
///   <item>When processing a background job or scheduled task</item>
///   <item>When handling a message from Kafka or another message broker</item>
///   <item>When initiating a new operation not tied to an existing request</item>
/// </list>
/// </para>
/// <para>
/// <b>When to Validate:</b>
/// <list type="bullet">
///   <item>When receiving a correlation ID from an external client</item>
///   <item>When extracting a correlation ID from message metadata</item>
///   <item>When importing data that includes correlation IDs</item>
/// </list>
/// </para>
/// <para>
/// Example usage:
/// <code><![CDATA[
/// // Generate a new correlation ID
/// var correlationId = CorrelationIdUtility.Generate();
///
/// // Validate a correlation ID from an external source
/// bool isValid = CorrelationIdUtility.IsValid(clientProvidedId);
/// if (!isValid)
/// {
///     // Generate a new one if invalid
///     correlationId = CorrelationIdUtility.Generate();
/// }
///
/// // Validate using the out parameter pattern
/// if (CorrelationIdUtility.TryParse(clientProvidedId, out var parsedId))
/// {
///     // Use the validated correlation ID
///     _correlationAccessor.CorrelationId = parsedId;
/// }
/// ]]></code>
/// </para>
/// </remarks>
public static class CorrelationIdUtility
{
    /// <summary>
    /// The prefix that identifies a string as a correlation ID.
    /// </summary>
    /// <remarks>
    /// This prefix is applied to all correlation IDs generated by <see cref="Generate"/>.
    /// It serves two purposes:
    /// <list type="number">
    ///   <item>Makes correlation IDs easily identifiable in logs, traces, and debugging tools</item>
    ///   <item>Prevents collision with GUIDs used for other purposes (entity IDs, tokens, etc.)</item>
    /// </list>
    /// </remarks>
    private const string Prefix = "corr_";

    /// <summary>
    /// The regular expression pattern used to validate correlation ID format.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This pattern validates that a correlation ID:
    /// <list type="number">
    ///   <item>Starts with the "corr_" prefix (case-sensitive)</item>
    ///   <item>Followed by a valid GUID in hyphenated format (8-4-4-4-12)</item>
    ///   <item>Contains only hexadecimal characters (0-9, a-f) in the GUID portion</item>
    ///   <item>Has no additional characters before or after</item>
    /// </list>
    /// </para>
    /// <para>
    /// Pattern breakdown:
    /// <list type="bullet">
    ///   <item><c>^</c> - Start of string</item>
    ///   <item><c>corr_</c> - Literal prefix</item>
    ///   <item><c>[0-9a-f]{8}</c> - 8 hex digits (first GUID segment)</item>
    ///   <item><c>-</c> - Literal hyphen</item>
    ///   <item><c>[0-9a-f]{4}</c> - 4 hex digits (second GUID segment)</item>
    ///   <item><c>-</c> - Literal hyphen</item>
    ///   <item><c>[0-9a-f]{4}</c> - 4 hex digits (third GUID segment)</item>
    ///   <item><c>-</c> - Literal hyphen</item>
    ///   <item><c>[0-9a-f]{4}</c> - 4 hex digits (fourth GUID segment)</item>
    ///   <item><c>-</c> - Literal hyphen</item>
    ///   <item><c>[0-9a-f]{12}</c> - 12 hex digits (fifth GUID segment)</item>
    ///   <item><c>$</c> - End of string</item>
    /// </list>
    /// </para>
    /// </remarks>
    private static readonly Regex s_validationPattern = new(
        $"^{Prefix}[0-9a-f]{{8}}-[0-9a-f]{{4}}-[0-9a-f]{{4}}-[0-9a-f]{{4}}-[0-9a-f]{{12}}$",
        RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    /// <summary>
    /// Generates a new correlation ID with a guaranteed unique value.
    /// </summary>
    /// <returns>
    /// A string containing a new correlation ID in the format <c>corr_{guid}</c>.
    /// </returns>
    /// <remarks>
    /// <para>
    /// This method generates a new correlation ID by creating a new GUID using
    /// <see cref="System.Guid.NewGuid"/> and prefixing it with <see cref="Prefix"/>.
    /// </para>
    /// <para>
    /// <b>Uniqueness Guarantee:</b><br/>
    /// The uniqueness of the generated correlation ID relies on <see cref="System.Guid.NewGuid"/>,
    /// which uses a cryptographically strong random number generator (CSPNG) to ensure
    /// practical uniqueness. The probability of collision is negligible for all practical purposes.
    /// </para>
    /// <para>
    /// <b>Performance Considerations:</b><br/>
    /// Guid generation is fast and does not require I/O or external coordination.
    /// This method can be called frequently without significant performance impact.
    /// </para>
    /// <para>
    /// <b>Thread Safety:</b><br/>
    /// This method is thread-safe. Concurrent calls will generate unique correlation IDs
    /// without any synchronization required.
    /// </para>
    /// <para>
    /// <b>Example Output:</b><br/>
    /// <c>corr_a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d</c>
    /// </para>
    /// </remarks>
    public static string Generate()
    {
        return $"{Prefix}{Guid.NewGuid():D}";
    }

    /// <summary>
    /// Validates whether the specified string is a well-formed correlation ID.
    /// </summary>
    /// <param name="correlationId">The correlation ID string to validate.</param>
    /// <returns>
    /// <c>true</c> if <paramref name="correlationId"/> is a valid correlation ID format;
    /// otherwise, <c>false</c>.
    /// </returns>
    /// <remarks>
    /// <para>
    /// This method validates the format of the correlation ID but does not verify
    /// whether it corresponds to an actual request or operation in the system.
    /// </para>
    /// <para>
    /// <b>Validation Rules:</b>
    /// <list type="bullet">
    ///   <item>Must not be null or empty</item>
    ///   <item>Must start with the "corr_" prefix (case-sensitive)</item>
    ///   <item>Must contain a valid GUID in hyphenated format after the prefix</item>
    ///   <item>Must not contain any additional characters or whitespace</item>
    /// </list>
    /// </para>
    /// <para>
    /// <b>Case Sensitivity:</b><br/>
    /// The prefix "corr_" is case-sensitive. "CORR_abc123" would be rejected.
    /// The GUID portion is case-insensitive, as GUIDs are conventionally represented
    /// in lowercase but uppercase is also valid.
    /// </para>
    /// <para>
    /// <b>Use Cases:</b><br/>
    /// Use this method when you need to validate a correlation ID but don't need
    /// to normalize or use it immediately. If you need to use the validated value,
    /// consider using <see cref="TryParse(string?, out string?)"/> instead.
    /// </para>
    /// </remarks>
    public static bool IsValid(string? correlationId)
    {
        if (string.IsNullOrWhiteSpace(correlationId))
        {
            return false;
        }

        return s_validationPattern.IsMatch(correlationId);
    }

    /// <summary>
    /// Attempts to validate and return the specified correlation ID.
    /// </summary>
    /// <param name="correlationId">The correlation ID string to validate.</param>
    /// <param name="normalizedId">
    /// When this method returns, contains the normalized correlation ID if validation succeeded;
    /// otherwise, <c>null</c>. This parameter is passed uninitialized.</param>
    /// <returns>
    /// <c>true</c> if <paramref name="correlationId"/> is a valid correlation ID format;
    /// otherwise, <c>false</c>.
    /// </returns>
    /// <remarks>
    /// <para>
    /// This method provides a convenient pattern for validating and using a correlation ID
    /// in a single operation. If validation succeeds, the output parameter contains the
    /// validated correlation ID (normalized to lowercase).
    /// </para>
    /// <para>
    /// <b>Normalization:</b><br/>
    /// The returned correlation ID is normalized to lowercase for consistency.
    /// While GUIDs are case-insensitive, storing and comparing them in a consistent case
    /// improves log readability and database indexing.
    /// </para>
    /// <para>
    /// <b>Example Usage:</b>
    /// <code><![CDATA[
    /// if (CorrelationIdUtility.TryParse(clientProvidedId, out var correlationId))
    /// {
    ///     _correlationAccessor.CorrelationId = correlationId;
    /// }
    /// else
    /// {
    ///     // Generate a new correlation ID if the provided one is invalid
    ///     _correlationAccessor.CorrelationId = CorrelationIdUtility.Generate();
    /// }
    /// ]]></code>
    /// </para>
    /// </remarks>
    public static bool TryParse(
        [NotNullWhen(true)] string? correlationId,
        out string? normalizedId)
    {
        if (!IsValid(correlationId))
        {
            normalizedId = null;
            return false;
        }

        normalizedId = correlationId!.ToLowerInvariant();
        return true;
    }
}
